training_pipeline_config:
  pipeline_name: rental_bike_demand
  artifact_dir: artifact

data_ingestion_config:
  dataset_download_url : https://github.com/Shivan118/Main-Branching/blob/main/Rental%20bike%20demand%20data.zip?raw=true
  raw_data_dir: raw_data
  tgz_download_dir: tgz_data
  ingested_dir: ingested_data
  ingested_train_dir: train
  ingested_test_dir: test